server:
  port: 9300
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      #defaultZone: http://netflix-eureka:8761/eureka #docker
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lms_db
      #uri: mongodb://mongodb:27017/lms_db #docker
springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_0
  cache:
    disabled: true