server:
  port: 9100
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: root
    password: password123
    #url: jdbc:postgresql://host.docker.internal:5432/faculty #docker
    url: jdbc:mysql://localhost:3306/lms_db
  jackson:
    serialization:
      fail-on-empty-beans: false
  cloud:
    config:
      override-none: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

eureka:
  client:
    serviceUrl:
      #defaultZone: http://netflix-eureka:8761/eureka #docker
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_0
  cache:
    disabled: true