server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888
      #uri: http://spring-cloud-config:8888
      failFast: true
    gateway:
      routes:
        - id: course_ms
          uri: http://localhost:9100
          predicates:
            - Path=/lms/course/**
        - id: user_ms
          uri: http://localhost:9200
          predicates:
            - Path=/lms/user/**
        - id: course_query_ms
          uri: http://localhost:9300
          predicates:
            - Path=/lms/course/**
        - id: eureka
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info